# Todo create playbooks for installing npm utilities
# like jshint, jsonlint checker, coffee-script
# same with ruby gems like teamocil
---
# This playbook deploys the dotfiles and utilities that I like to have around while
# developing.
- name: copy all dotfiles to the home directory and install commonly used utilities
  # Have to run localhost seperate from other servers as need to ask for password
  # locally but not remote and ansible can't handle this use case yet.
  #hosts: localhost
  hosts: all:!localhost


  tasks:
    - name: create group by operating system
      action: group_by key={{ansible_os_family}}

    # Install things common across different OSs
    - include: tasks/dotfiles.yml
    - include: tasks/nodejs_utilities.yml
    - include: tasks/ruby_gem_utilities.yml
    - include: tasks/vim.yml

    - name: install z, a quick jump utility
      git: repo=https://github.com/rupa/z.git dest=/usr/local/z
      tags:
        - z
        - install
      sudo: yes

- hosts: Darwin
  tasks:
    - include: tasks/macosx.yml

#- hosts: Debian
  #tasks:
    #- include: tasks/debian.yml

- hosts: RedHat
  tasks:
    - include: tasks/redhat.yml
