---
# This playbook deploys the dotfiles and utilities that I like to have around while
# developing.
- name: copy all dotfiles to the home directory and install commonly used utilities
  # Have to run localhost seperate from other servers as need to ask for password
  # locally but not remote and ansible can't handle this use case yet.
  hosts: localhost
  #hosts: all:!localhost

  tasks:
    - name: create group by operating system
      action: group_by key={{ansible_os_family}}
      tags: testing

- hosts: Darwin
  tasks:
    - include: tasks/macosx.yml
    - include: tasks/dotfiles.yml
    # - include: tasks/nodejs_utilities.yml
      #- include: tasks/vim.yml
    - include: tasks/utilities.yml
    # - include: tasks/python_utilities.yml

- hosts: Debian
  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/debian.yml
    - include: tasks/nodejs_utilities.yml
    - include: tasks/vim.yml
    - include: tasks/utilities.yml
    - include: tasks/python_utilities.yml

- hosts: RedHat
  tasks:
    - include: tasks/redhat.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nodejs_utilities.yml
    - include: tasks/vim.yml
    - include: tasks/utilities.yml
    - include: tasks/python_utilities.yml
