# Todo create playbooks for installing npm utilities
# like jshint, jsonlint checker, coffee-script
# same with ruby gems like teamocil
---
# This playbook deploys the dotfiles and utilities that I like to have around while
# developing.
- name: copy all dotfiles to the home directory and install commonly used utilities
  # Have to run localhost seperate from other servers as need to ask for password
  # locally but not remote and ansible can't handle this use case yet.
  #hosts: localhost
  #hosts: all:!localhost
  hosts: onebox

  tasks:
    - name: create group by operating system
      action: group_by key={{ansible_os_family}}

- hosts: Darwin
  tasks:
    - include: tasks/macosx.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nodejs_utilities.yml
    - include: tasks/ruby_gem_utilities.yml
    - include: tasks/vim.yml
    - include: tasks/git_extras.yml
    - include: tasks/utilities.yml

- hosts: Debian
  tasks:
    - include: tasks/debian.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nodejs_utilities.yml
    - include: tasks/ruby_gem_utilities.yml
    - include: tasks/vim.yml
    - include: tasks/git_extras.yml
    - include: tasks/utilities.yml
    - include: tasks/the_silver_searcher_from_source.yml

- hosts: RedHat
  tasks:
    - include: tasks/redhat.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nodejs_utilities.yml
    - include: tasks/ruby_gem_utilities.yml
    - include: tasks/vim.yml
    - include: tasks/git_extras.yml
    - include: tasks/utilities.yml
    - include: tasks/the_silver_searcher_from_source.yml
