---
- name: Install development tools and dotfiles
  hosts: all
  gather_facts: true

  vars:
    user_home: "{{ ansible_facts['user_dir'] }}"

  handlers:
    - name: Refresh apt metadata
      ansible.builtin.apt:
        update_cache: true
      become: true

  tasks:
    - name: Install macOS packages and settings
      ansible.builtin.include_tasks: tasks/macosx.yml
      when: ansible_facts.os_family == "Darwin"

    - name: Install Debian packages and settings
      ansible.builtin.include_tasks: tasks/debian.yml
      when: ansible_facts.os_family == "Debian"

    - name: Install Red Hat packages
      ansible.builtin.include_tasks: tasks/redhat.yml
      when: ansible_facts.os_family == "RedHat"

    - name: Install dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yml

    - name: Install common utilities
      ansible.builtin.include_tasks: tasks/utilities.yml

    - name: Install Neovim package manager
      ansible.builtin.include_tasks: tasks/vim.yml

    - name: Install Node.js utilities
      ansible.builtin.include_tasks: tasks/nodejs_utilities.yml
