# Todo create playbooks for installing npm utilities
# like jshint, jsonlint checker, coffee-script
# same with ruby gems like teamocil
---
# This playbook deploys the dotfiles and utilities that I like to have around while
# developing.
- name: copy all dotfiles to the home directory and install commonly used utilities
  # Have to run localhost seperate from other servers as need to ask for password
  # locally but not remote and ansible can't handle this use case yet.
  #hosts: localhost
  hosts: all:!localhost

  vars:
    username: kyle

  tasks:
    - include: tasks/dotfiles.yml

    - name: install z, a quick jump utility
      git: repo=https://github.com/rupa/z.git dest=/usr/local/z
      tags:
        - z
        - install
      sudo: yes

    # TODO split os into seperate files and load conditionally.
    # for macs, install download git prompt file and source it in bashrc file
    # per http://stackoverflow.com/questions/12870928/mac-bash-git-ps1-command-not-found
    - include: tasks/macosx.yml
      when: ansible_os_family == "Darwin"

    - include: tasks/debian.yml
      when: ansible_os_family == "Debian"

    - include: tasks/redhat.yml
      when: ansible_os_family == "RedHat"
