- name: install .bash_profile
  action: template src=templates/bash_profile dest=~/.bash_profile
  tags: dotfile

- name: install .bashrc
  action: template src=templates/bashrc dest=~/.bashrc
  tags: dotfile

- name: install config.fish
  action: template src=templates/config.fish dest=~/.config/fish/config.fish
  tags: dotfile

- name: install .gitconfig
  action: template src=templates/gitconfig dest=~/.gitconfig
  tags: dotfile

- name: install nvim init.vim
  action: template src=templates/init.vim dest=~/.config/nvim/init.vim
  tags: dotfile

- name: install .gitignore_global
  action: template src=templates/gitignore_global dest=~/.gitignore_global
  tags: dotfile

- name: install git auto-complete library
  get_url: url=https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh dest=~/.git-prompt.sh

- name: install .inputrc
  action: template src=templates/inputrc dest=~/.inputrc
  tags: dotfile
