- name: Check for installed apps(casks)
  shell: brew cask list | grep {{ item }}
  register: installed_applications
  with_items: applications
  ignore_errors: true

- name: Install apps with brew-cask
  shell: brew cask install {{ item }}
  with_items: applications
  when: "item not in installed_applications.results|map(attribute='stdout')"

- name: Enable quicklook plugins (which just got installed)
  command: qlmanage -r
