---
- name: Install common packages on Red Hat machines
  ansible.builtin.dnf:
    name:
      - ctags
      - mosh
      - neovim
      - nodejs
      - npm
      - smem
      - tmux
      - xz-devel
    state: present
  become: true
  tags: install
