- name: See if the silver searcher is installed
  shell: "[ -e /usr/local/bin/ag ] && echo 'Found' || echo ''"
  register: ag_installed
- name: download the silver searcher source
  git: repo=https://github.com/ggreer/the_silver_searcher.git dest=/tmp/the_silver_searcher
  when: (not ag_installed.stdout)
- name: build silver searcher from source
  command: ./build.sh chdir=/tmp/the_silver_searcher/
  when: (not ag_installed.stdout)
  sudo: yes
- name: run make install
  command: make install chdir=/tmp/the_silver_searcher/
  when: (not ag_installed.stdout)
  sudo: yes
