---
- name: Install z directory jumper
  ansible.builtin.git:
    repo: https://github.com/rupa/z.git
    dest: "{{ user_home }}/.z"
    version: master
    update: "{{ upgrade_system_packages | default(false) | bool }}"
  tags:
    - install
    - z

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ user_home }}/.oh-my-zsh"
    version: master
    update: "{{ upgrade_system_packages | default(false) | bool }}"
