---
- name: Install personal Kickstart Neovim config
  ansible.builtin.git:
    repo: https://github.com/KyleAMathews/kickstart.nvim.git
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    version: master
    update: false
