# Stop here for non-interactive shells.
case $- in
  *i*) ;;
  *) return ;;
esac

export EDITOR=nvim
export VISUAL=nvim
export GOPATH="$HOME/gocode"
export N_PREFIX="${N_PREFIX:-$HOME/.n}"
export PATH="$N_PREFIX/bin:$HOME/.local/bin:$HOME/bin:$GOPATH/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

alias g='git'
alias vi='nvim'
alias vim='nvim'

if [ -f "$HOME/.git-prompt.sh" ]; then
  source "$HOME/.git-prompt.sh"
fi

if [ -f "$HOME/.z/z.sh" ]; then
  source "$HOME/.z/z.sh"
elif [ -f /opt/homebrew/etc/profile.d/z.sh ]; then
  source /opt/homebrew/etc/profile.d/z.sh
fi

if [ -f "$HOME/.cargo/env" ]; then
  source "$HOME/.cargo/env"
fi
